### ISSUE TITLE
Make space between entity value and unit configurable

### ISSUE THREAD

**Issue by matban666** [matban666/tesla-style-solar-power-card#3]
This was removed to save space but some users like it so make it a config option.

**Comment by matban666** [comment]
Added yaml config keys:
show_space_before_power_units
show_space_before_all_units

These are optional can be set to true or false, if not present they will be defaulted to false.
show_space_before_all_units takes precedence over show_space_before_power_units

Following has example has:
show_space_before_power_units: true

![image](https://user-images.githubusercontent.com/121500633/227208377-3098f756-6e3d-419c-81a4-cf8a494ba6f5.png)

**Comment by matban666** [comment]
This branch has been merged into master.

**Comment by caitotheonlypotato** [comment]
works beautifully
